name: Demo to create automatic PR
        
on:
  push:
    branches:
      - "PreProd"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Raise PR
              uses: peter-evans/create-pull-request@v3
              with:
                  token: ${{secrets.GITHUB_TOKEN}}
                  title: "demo for auto pr"
                  delete-branch: false
