on:
  push:
    branches: [Master]
name: create-pull-request workflow
jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: repo-sync/pull-request@v2
        name: pull-request
        with:
          destination_branch: "PreProd"
          pr_title: "Pulling ${{ github.ref }} into main"
          pr_body: "👑 *An automated PR*"
          pr_reviewer: "kingdonb"
          pr_draft: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
