name: Demo to create automatic PR
        
on:
  push:
    branches:
      - "Master"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checking out code
              uses: actions/checkout@v2

            - name: Raise PR
              uses: peter-evans/create-pull-request@v3
              with:
                  branch: "PreProd"
                  base: "Master"
                  title: "demo for auto pr"
                  token: ${{secrets.GITHUB_TOKEN}}
                  delete-branch: false
