on:
  workflow_dispatch:
name: create-pull-request workflow
jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: checkout

      - uses: repo-sync/pull-request@v2
        name: pull-request
        with:
          destination_branch: "PreProd"
          pr_title: "Pulling ${{ github.ref }} into PreProd"
          pr_body: "👑 *An automated PR*"
          pr_reviewer: "Shayam-S3"
          pr_draft: false
          github_token: ${{ secrets.GITHUB_TOKEN }}
